### ISSUE TITLE
Continue playing modules in "search mode"

### ISSUE THREAD

**Issue by marekhac** [sitomani/4champ#34]
Hi! Is there a chance to play modules one by one in search mode ? Now, after module end, next module is taken from my past listenings

I dream about something like this:

- I tap on SEARCH on bottom bar
- choose Composer and type Jazzcat
- I've got a list of his modules (great modules BTW ;)
- I choose and play module called "call me mr. cox"
- When module end I expect to play next module from the list ("Cat-ah-pull-tah")

![Screenshot 2024-03-12 at 21 23 30](https://github.com/sitomani/4champ/assets/15977848/c10b4015-bdb8-4a07-9b62-fb04c8f0679f)

**Comment by sitomani** [comment]
I have started working on this feature as "Artist radio" that you can turn on the search results page and integrating it with the radio UI.

**Comment by sitomani** [comment]
Implemented in https://github.com/sitomani/4champ/commit/677344a325171eed2c8a6df9c0c2ebc0285cfa73 and published in AppStore release 3.7 as of this week.

**Comment by marekhac** [comment]
> Implemented in [677344a](https://github.com/sitomani/4champ/commit/677344a325171eed2c8a6df9c0c2ebc0285cfa73) and published in AppStore release 3.7 as of this week.

Works great! THANK YOU!
